import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./globals.css";

const robot = Roboto({
  subsets: ["latin"],
  weight: ["400", "500", "700"],
  variable: "--font-roboto",
});

export const metadata: Metadata = {
  title: "Letter Z",
  description: "Generated By Miracle",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${robot.variable} antialiased`}>{children}</body>
    </html>
  );
}
